### ISSUE TITLE
DataParallel implementation

### ISSUE THREAD

**Issue by unademo** [saic-vul/adaptis#15]
Since training on a single GPU is hard, can you implement the codes under the DataParallel mode? Thx.

**Comment by unademo** [comment]
It comes out the error:
```TypeError: __new__() missing 1 required positional argument: 'semantic'```
after I added DataParallel to the ```self.net```.

**Comment by unademo** [comment]
I have temporarily solved the error ```TypeError: __new__() missing 1 required positional argument: 'semantic'``` when using DataParallel by modifying ```adaptis/adaptis/model/adaptis.py```:
1. First I found that [```self.make_named_outputs(outputs)```](https://github.com/saic-vul/adaptis/blob/pytorch/adaptis/model/adaptis.py#L68) returns a static ```namedtuple```(collections.namedtuple) object, which is not a common type of data structure. 
Since the model trained on the DataParallel, outputs of ```self.make_named_outputs(outputs)```, calculated by multiple gpus, will be gathered into one variable, which realized in pytorch lib ([```pytorch/torch/nn/parallel/scatter_gather.py```](https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/scatter_gather.py#L52) )
Obviously, after the gathering, data in the outputs goes wrong. So I hacked a lot to make it normal after the gathering.
2. I have tried: modifying the construction of the namedtuple, writing myself data structure and modifying the ```torch/nn/parallel/scatter_gather.py```. But they all failed.
3. Finally, I trace back to the [calling](https://github.com/saic-vul/adaptis/blob/pytorch/adaptis/engine/trainer.py#L284). After forwarding the ```self.net```, it will call the fields "instance", "semantic" and "proposals" of the ```output```. So I convert the ```outputs``` in [the method ```forward``` of class ```AdaptIS```](https://github.com/saic-vul/adaptis/blob/pytorch/adaptis/model/adaptis.py#L43) into ```dict```, which is formatted as 
```self.outputs={'instances':None, 'semantic':None, 'proposals':None}```
Everything goes OK.
BTW, also you need to modify the ```output``` in ```adaptis/engine/trainer.py```, e.g. ```output.instance``` -> ```output['instance']```

**Comment by shoutOutYangJie** [comment]
Hello, How does AdaptIS's performance? Do you train it on CityScape?

**Comment by unademo** [comment]
> Hello, How does AdaptIS's performance? Do you train it on CityScape?

Nope. I haven't tried it on CityScape.
