### ISSUE TITLE
Please provide the larger images in toy data for test.

### ISSUE THREAD

**Issue by DIYer22** [saic-vul/adaptis#3]
AdaptIS is a very good method, thank you for sharing this awesome work.

I want to try AdaptIS on large image with dense objects. So, could you please provide  the larger images in Figure 3 (d) that for test.

![image](https://user-images.githubusercontent.com/10448025/65670673-62374f00-e078-11e9-888c-563f79ba4861.png)

**Comment by ksofiyuk** [comment]
I have updated the [notebook](https://github.com/saic-vul/adaptis/blob/master/notebooks/test_toy_model.ipynb) with the example of testing on the large sample. You can find these images [here](https://github.com/saic-vul/adaptis/tree/master/images/toy_samples).
You can also try to train our model on enlarged toy dataset with denser coverage of objects:
https://drive.google.com/file/d/1slSP7p8WJi8NOIdLUCQKaydlmwHDgT_M

**Comment by DIYer22** [comment]
Thanks a lot!
