### ISSUE TITLE
Would you please provide one pretrained model for toy dataset?

### ISSUE THREAD

**Issue by wangxiao5791509** [saic-vul/adaptis#7]
I want to first run the test code. Would you please provide one pretrained model for toy dataset? Thanks.

**Comment by ksofiyuk** [comment]
Pretrained model for ToyV1: https://drive.google.com/open?id=1IuJUh0JvbKYILBxCeO2h6U4LG-9DoTHi
Pretrained model for ToyV2: https://drive.google.com/open?id=1RxepfpJF5gRpRNYu1urdV748suF3TL5k

**Comment by shoutOutYangJie** [comment]
Have you test it on provoided pretrained model? why do these pretrained model have small size. just 26MB.

**Comment by shoutOutYangJie** [comment]
> Have you test it on provoided pretrained model? why do these pretrained model have small size. just 26MB.

@ksofiyuk
